### ISSUE TITLE
Suggestion: Do you mind adding an option to pause the game when opening the window?

### ISSUE THREAD

**Issue by lisanhu** [Zeracronius/DynamicTradeInterface#34]
Hi! Thank you for your great work!

Do you mind adding an option to pause the game when opening the window?

Actually I already have implemented it at https://github.com/lisanhu/rimworld-DynamicTradeInterface.git

I'm trying to ask what is your opinion about this added functionality, to decide whether to create a PR or hide it.

Thank you again for your work! I love it! It has a huge performance gain!

**Comment by Zeracronius** [comment]
The code is fine, however it already should be force pausing whenever the trade window is opened. When and where are you experiencing this not being the case?
Specifically, this line should handle the pausing:
https://github.com/Zeracronius/DynamicTradeInterface/blob/9eaa0053b6bbb34e023e0d58f12d187010c980a4/Source/DynamicTradeInterface/UserInterface/Window_DynamicTrade.cs#L142

I'm going to look into if this behaviour is broke in 1.5.

**Comment by Zeracronius** [comment]
Looking closer at your code, i see that you are applying it in the configuration window, but that should be accessible only while the trade window is already open or when you are in main menu?

**Comment by Zeracronius** [comment]
Forced pause still works as expected in 1.5

**Comment by lisanhu** [comment]
Sorry maybe my presentation was not clear. By pausing the game, I mean when exiting the trade window :smile:

**Comment by Zeracronius** [comment]
Feel free to open the pull request for it, i'll do some minor adjustments to the phrasing after to have it be something like "Sustain pause" to clarify that already pauses while the window is open.
