### ISSUE TITLE
Support for Weapon and Apparel Quality Indicators

### ISSUE THREAD

**Issue by Callipygia** [Zeracronius/DynamicTradeInterface#35]
Alternative to Quality Colors, more performance friendly.

https://steamcommunity.com/sharedfiles/filedetails/?id=2005333573

**Comment by Zeracronius** [comment]
Having looked into Weapon and Apparel Quality Indicators' source code, it does not seem to expose the quality colour in an accessible way.
It would unfortunately require coupling too tightly on my side to support it.
