### ISSUE TITLE
Random's Gene Assistant Compatibility

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [Zeracronius/DynamicTradeInterface#5]
Current C# patch capability only supports adding new columns, but In order to write a patch for [Random's Gene Assistant](https://steamcommunity.com/sharedfiles/filedetails/?id=2882497271), I need access to the entire row's `Rect`, so I can color it accordingly. Is this something you are interested in adding support for?

**Comment by Zeracronius** [comment]
Would using icons similar to all the other indicators and techprints not be a more consistent and cleaner solution?

Tech prints is something i would like to include, and i looked into the gene assistant, but it is coded in what seems to be a really unperformant way.
Everything can add extra icons, but only one thing would ever be able to control row color

**Comment by Zeracronius** [comment]
https://github.com/TedStumpf/RandomsGeneAssistant/blob/83aff5743359857b4c323688ecacb470d21c3e96/source/PatchTradeUIRevisited.cs

If am not mistaken, every single frame for every single genepack row it scans the active map for all genebanks and then iterates the content of all of them to figure out what genes you do and don't have. And then uses that to decide color.

You are not going to be changing what genes you do and don't have during a trade session while the game is paused. There is no reason to check it repeatedly.

I don't know enough about genepacks and genes to write this code, and while i could copy and adapt the code from that mod, i don't want to copy other people's code.
However if i could, i would implement it the same way as xenotypes in ExtraIcons column.
Do all the checking and testing in PostOpen and cache it, ans then display it as an extra icon with tooltip on genepacks.

**Comment by Ryan-rsm-McKenzie** [comment]
Wow I didn't know it was so inefficient. I agree that doing something similar to techprints would be a good idea.

**Comment by Ryan-rsm-McKenzie** [comment]
Ok so I came up with an icon based solution that uses custom shaders to recolor the genepack icon as an indicator of what the player has collected so far. Let me know what you think.
![image2](https://github.com/Zeracronius/DynamicTradeInterface/assets/10575995/fb727248-4983-44f6-a27a-583ac658d78d)

**Comment by Zeracronius** [comment]
I think that looks good! I will check the PR now.
